### ISSUE TITLE
Add a version number

### ISSUE THREAD

**Issue by alanyee** [alanyee/valorantbp#20]
### Is your feature request related to a problem? Please describe

When reporting an issue, users may simply have an older version of the cli that is bugged or does not have the requested feature, but the cli in its latest version may no longer bugged or has the feature. I would like the CLI to have versioning.

### Describe the solution you'd like

The version should be able to be printed out via argparse `'version'` action: https://docs.python.org/3/library/argparse.html#action

**Comment by Dhi13man** [comment]
Added #21 to fix this. Please review and merge. It is a lightweight change.
