### ISSUE TITLE
Automatically set data to next week once mission value is set to 0

### ISSUE THREAD

**Issue by alanyee** [alanyee/valorantbp#31]
### Is your feature request related to a problem? Please describe

I always find myself setting the mission counter to 0, and then I realize that I have to the week value to the next week in order to keep track when the next weekly missions are going to be refreshed which then requires that I reset the week value to 3 in anticipation of the weekly refresh.

### Describe the solution you'd like

Once the user sets the mission value to 0, the week value should increment and then the mission value should be reset to 3. This should only occur if the user does not set the week value while setting the mission value to 0. If it is the last week, the week value should not increment, though there is no business logic bug if the week value does increment for the last week.

**Comment by SasikaSankalana** [comment]
Hey, I would like to work on this issue. Can I get assigned to this?
