### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by alanyee** [alanyee/valorantbp#5]
## Describe the ideal solution or feature request
Add `CONTRIBUTING.md` according to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| Small| Important to help and guide contributors | Daily|

## How does this tie into our current application?
It helps contributors improve this project.

**Comment by aryan-errs** [comment]
Can i work on this?

**Comment by alanyee** [comment]
@salted0dreams Go for it!

**Comment by alanyee** [comment]
This should also mention an explicit style guide like https://peps.python.org/pep-0008/
