### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by alanyee** [alanyee/valorantbp#7]
## Describe the ideal solution or feature request
Add `CODE_OF_CONDUCT.md` according to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| Small| Important to help and guide contributors | Daily|

## How does this tie into our current application?
It helps contributors improve this project.

**Comment by aryan-errs** [comment]
Can i work on this?

**Comment by alanyee** [comment]
@salted0dreams Yes
